const fs = require('fs');
const path = require('path');
const assert = require('assert');
const workflow = JSON.parse(fs.readFileSync(path.resolve(__dirname, '..', 'n8n', 'API_Services', 'API_Execute.json'), 'utf8'));
const nodes = new Map(workflow.nodes.map((node) => [node.name, node]));
const code = nodes.get('Validate API Request').parameters.jsCode;
const targets = (name, output = 0) => (workflow.connections[name]?.main?.[output] || []).map((edge) => edge.node);
const run = (input) => new Function('$', code)((name) => ({ first: () => ({ json: name === 'Enforce API Capability' ? input : {} }) }))[0].json.validation;
assert.deepStrictEqual(targets('Is API Authorized? (Execute)', 0), ['Validate API Request']);
assert.deepStrictEqual(targets('Validate API Request'), ['Is API Request Valid?']);
assert.deepStrictEqual(targets('Is API Request Valid?', 0), ['Build Execute SQL']);
assert.deepStrictEqual(targets('Is API Request Valid?', 1), ['Prepare Audit - Execute Validation Error']);
assert.strictEqual(run({ body: { ApiCode: '@cong_no_chi_tiet', params: {} } }).code, 'VALIDATION_ERROR');
assert.strictEqual(run({ body: { ApiCode: '@hoa_don_chi_tiet', params: { '@DocumentID': 'HD1' } } }).ok, true);
assert.strictEqual(run({ body: { ApiCode: '@doanh_so', params: { '@TopN': 201 } } }).ok, false);
assert.strictEqual(run({ body: { ApiCode: '@doanh_so', params: { '@TuNgay': '2026-07-20', '@DenNgay': '2026-07-01' } } }).ok, false);
assert.strictEqual(run({ body: { ApiCode: '@lap_don_hang', params: {} } }).ok, true);
const inbound = Object.entries(workflow.connections).flatMap(([source, value]) => (value.main || []).flat().filter(Boolean).map((edge) => ({ source, target: edge.node }))).filter((edge) => edge.target === 'MS SQL Execute');
assert.deepStrictEqual(inbound, [{ source: 'Build Execute SQL', target: 'MS SQL Execute' }]);
console.log('API Execute validation tests passed.');
