/*
  Medstand AI-only order mutation.
  - Business DocumentID is generated by SQL.
  - Request idempotency is stored by hash and committed atomically with the order.
  - Price, promotion, stock, customer scope and authenticated user scope are rechecked server-side.
  This procedure does not alter dbo.API_DonHang_Insert used by other systems.
*/
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE dbo.API_DonHangChiTiet_Insert_AI
    @Username VARCHAR(50) = '',
    @DocumentID VARCHAR(50) = '',
    @DocumentDate DATETIME = NULL,
    @BranchID VARCHAR(50) = '',
    @ObjectID VARCHAR(50) = '',
    @Memo NVARCHAR(200) = '',
    @Notes NVARCHAR(MAX) = '',
    @XaPhuong NVARCHAR(50) = '',
    @ThuDiTuyen NVARCHAR(10) = '',
    @ItemList NVARCHAR(MAX) = '',
    @IdempotencyKey VARCHAR(128) = '',
    @RequestID VARCHAR(100) = ''
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @ResultMsg NVARCHAR(500) = N'';
    DECLARE @ResultCode VARCHAR(60) = '';
    DECLARE @InternalError NVARCHAR(2000) = N'';
    DECLARE @AuditInfo NVARCHAR(MAX) = N'';
    DECLARE @ManagerID VARCHAR(50) = '';
    DECLARE @EmployeeID VARCHAR(50) = '';
    DECLARE @CeoID VARCHAR(50) = '';
    DECLARE @UserBranchID VARCHAR(50) = '';
    DECLARE @Phone VARCHAR(150) = '';
    DECLARE @IsGlobal BIT = 0;
    DECLARE @IsManager BIT = 0;
    DECLARE @ApiCode VARCHAR(100) = 'API_DonHangChiTiet_Insert_AI';
    DECLARE @RequiredCapability VARCHAR(100) = 'orders.write';
    DECLARE @IdempotencyKeyHash CHAR(64) = NULL;
    DECLARE @VerifiedUserHash CHAR(64) = NULL;
    DECLARE @RequestFingerprintHash CHAR(64) = NULL;
    DECLARE @CanonicalItems NVARCHAR(MAX) = N'';
    DECLARE @StoredStatus VARCHAR(20) = NULL;
    DECLARE @StoredFingerprintHash CHAR(64) = NULL;
    DECLARE @StoredDocumentID VARCHAR(100) = NULL;
    DECLARE @StoredMsg NVARCHAR(500) = NULL;
    DECLARE @StoredMsgType INT = NULL;
    DECLARE @OrderActorConfig NVARCHAR(200) = NULL;

    SET @Username = LTRIM(RTRIM(COALESCE(@Username, '')));
    SET @DocumentID = LTRIM(RTRIM(COALESCE(@DocumentID, '')));
    SET @BranchID = LTRIM(RTRIM(COALESCE(@BranchID, '')));
    SET @ObjectID = LTRIM(RTRIM(COALESCE(@ObjectID, '')));
    SET @IdempotencyKey = LTRIM(RTRIM(COALESCE(@IdempotencyKey, '')));
    SET @RequestID = LTRIM(RTRIM(COALESCE(@RequestID, '')));
    SET @DocumentDate = COALESCE(@DocumentDate, GETDATE());

    IF NOT EXISTS (SELECT 1 FROM dbo.SY_User WHERE UserName = @Username AND COALESCE(Disable, 0) = 0)
    BEGIN
        SET @ResultCode = 'INVALID_USER';
        SET @ResultMsg = N'Tài khoản không tồn tại hoặc đã bị khóa';
        GOTO ReturnFailure;
    END;

    SELECT @UserBranchID = COALESCE(BranchID, ''),
           @ManagerID = COALESCE(ManagerID, ''),
           @EmployeeID = COALESCE(EmployeeID, ''),
           @CeoID = COALESCE(CeoID, ''),
           @IsGlobal = CASE WHEN UserGroupID IN ('Admin', 'SADM', 'BGD', 'GD') THEN 1 ELSE 0 END,
           @IsManager = COALESCE(Manager, 0)
    FROM dbo.SY_User
    WHERE UserName = @Username;

    /*
      Tài khoản trình diễn có thể không liên kết nhân viên ERP thật. Chỉ manager
      thuộc nhóm global mới được dùng actor override đã APPROVED; không suy actor
      từ dữ liệu client và không nới lỏng các kiểm tra khách hàng/kho/chi nhánh.
    */
    IF @EmployeeID = '' AND @IsManager = 1 AND @IsGlobal = 1
       AND OBJECT_ID(N'dbo.AI_BusinessRuleConfigTbl', N'U') IS NOT NULL
    BEGIN
        SELECT TOP (1) @OrderActorConfig = C.ConfigValue
        FROM dbo.AI_BusinessRuleConfigTbl C
        WHERE C.RuleCode = 'BR-ORDER-ACTOR-001'
          AND C.ConfigKey = LOWER(@Username)
          AND C.ValueType = 'JSON'
          AND C.Status = 'APPROVED'
          AND (C.EffectiveFrom IS NULL OR C.EffectiveFrom <= SYSUTCDATETIME())
          AND (C.EffectiveTo IS NULL OR C.EffectiveTo > SYSUTCDATETIME())
        ORDER BY C.EffectiveFrom DESC, C.RuleConfigID DESC;

        IF @OrderActorConfig IS NOT NULL
        BEGIN
            IF ISJSON(@OrderActorConfig) <> 1
               OR COALESCE(JSON_VALUE(@OrderActorConfig, '$.EmployeeID'), '') = ''
            BEGIN
                SET @ResultCode = 'ORDER_ACTOR_CONFIG_INVALID';
                SET @ResultMsg = N'Cấu hình người lập đơn không hợp lệ';
                GOTO ReturnFailure;
            END;

            SET @EmployeeID = LTRIM(RTRIM(JSON_VALUE(@OrderActorConfig, '$.EmployeeID')));
            IF @UserBranchID = ''
                SET @UserBranchID = LTRIM(RTRIM(COALESCE(JSON_VALUE(@OrderActorConfig, '$.BranchID'), '')));
        END;
    END;

    IF @UserBranchID = '' OR @EmployeeID = ''
    BEGIN
        SET @ResultCode = 'USER_SCOPE_INCOMPLETE';
        SET @ResultMsg = N'Tài khoản chưa được gán đầy đủ chi nhánh hoặc nhân viên';
        GOTO ReturnFailure;
    END;

    IF @BranchID = '' SET @BranchID = @UserBranchID;
    IF @BranchID <> @UserBranchID
    BEGIN
        SET @ResultCode = 'BRANCH_OUT_OF_SCOPE';
        SET @ResultMsg = N'Chi nhánh tạo đơn không thuộc tài khoản đăng nhập';
        GOTO ReturnFailure;
    END;

    IF CAST(@DocumentDate AS DATE) < CAST(GETDATE() AS DATE)
    BEGIN
        SET @ResultCode = 'INVALID_DOCUMENT_DATE';
        SET @ResultMsg = N'Ngày đơn hàng không được nhỏ hơn ngày hiện tại';
        GOTO ReturnFailure;
    END;

    IF LEN(@DocumentID) > 30
    BEGIN
        SET @ResultCode = 'DOCUMENT_ID_TOO_LONG';
        SET @ResultMsg = N'Mã đơn hàng vượt giới hạn 30 ký tự';
        GOTO ReturnFailure;
    END;

    IF LEN(COALESCE(@Memo, N'')) > 200 OR LEN(COALESCE(@XaPhuong, N'')) > 50 OR LEN(COALESCE(@ThuDiTuyen, N'')) > 10
    BEGIN
        SET @ResultCode = 'HEADER_VALUE_TOO_LONG';
        SET @ResultMsg = N'Ghi chú, phường/xã hoặc tuyến đi vượt độ dài cho phép';
        GOTO ReturnFailure;
    END;

    IF LEN(@IdempotencyKey) < 8 OR LEN(@IdempotencyKey) > 128
       OR @IdempotencyKey LIKE '%[^A-Za-z0-9._:-]%'
    BEGIN
        SET @ResultCode = 'IDEMPOTENCY_KEY_REQUIRED';
        SET @ResultMsg = N'Yêu cầu tạo đơn thiếu khóa chống gửi lặp hợp lệ';
        GOTO ReturnFailure;
    END;

    IF LEN(@RequestID) < 8 OR LEN(@RequestID) > 100
       OR @RequestID LIKE '%[^A-Za-z0-9._:-]%'
    BEGIN
        SET @ResultCode = 'REQUEST_ID_REQUIRED';
        SET @ResultMsg = N'Yêu cầu tạo đơn thiếu mã request hợp lệ';
        GOTO ReturnFailure;
    END;

    IF OBJECT_ID('dbo.AI_API_MutationIdempotency', 'U') IS NULL
    BEGIN
        SET @ResultCode = 'IDEMPOTENCY_LEDGER_UNAVAILABLE';
        SET @ResultMsg = N'Hệ thống chống gửi lặp chưa sẵn sàng. Không tạo đơn hàng. Mã đối soát: ' + @RequestID;
        GOTO ReturnFailure;
    END;

    IF OBJECT_ID('dbo.AI_WriteAuditLog', 'P') IS NULL
    BEGIN
        SET @ResultCode = 'AUDIT_UNAVAILABLE';
        SET @ResultMsg = N'Hệ thống audit chưa sẵn sàng. Không tạo đơn hàng. Mã đối soát: ' + @RequestID;
        GOTO ReturnFailure;
    END;

    IF COALESCE(@ObjectID, '') = '' OR NOT EXISTS (SELECT 1 FROM dbo.CF_ObjectTbl WHERE ObjectID = @ObjectID)
    BEGIN
        SET @ResultCode = 'CUSTOMER_NOT_FOUND';
        SET @ResultMsg = N'Khách hàng không tồn tại';
        GOTO ReturnFailure;
    END;

    IF NOT EXISTS (SELECT 1 FROM dbo.AR_GetObjectByUserFnc(@Username) WHERE ObjectID = @ObjectID)
    BEGIN
        SET @ResultCode = 'CUSTOMER_OUT_OF_SCOPE';
        SET @ResultMsg = N'Bạn không có quyền tạo đơn cho khách hàng này';
        GOTO ReturnFailure;
    END;

    SELECT @Phone = COALESCE(Phone, '') FROM dbo.CF_ObjectTbl WHERE ObjectID = @ObjectID;
    IF @Phone = ''
    BEGIN
        SET @ResultCode = 'CUSTOMER_PHONE_REQUIRED';
        SET @ResultMsg = N'Số điện thoại khách hàng chưa có';
        GOTO ReturnFailure;
    END;

    IF COALESCE(@ItemList, '') = '' OR ISJSON(@ItemList) <> 1
    BEGIN
        SET @ResultCode = 'INVALID_ITEM_LIST';
        SET @ResultMsg = N'Danh sách sản phẩm không hợp lệ';
        GOTO ReturnFailure;
    END;

    DECLARE @AllowedStores TABLE (StoreHouseID VARCHAR(50) PRIMARY KEY);
    DECLARE @StockAsOfUtc DATETIME2(0) = SYSUTCDATETIME();
    DECLARE @StockRuleVersion VARCHAR(30) = NULL;

    INSERT @AllowedStores (StoreHouseID)
    SELECT StoreHouseID
    FROM dbo.AI_WarehouseByUserFnc(@Username, @StockAsOfUtc);

    SELECT TOP (1) @StockRuleVersion = RuleVersion
    FROM dbo.AI_WarehouseByUserFnc(@Username, @StockAsOfUtc);

    IF NOT EXISTS (SELECT 1 FROM @AllowedStores)
    BEGIN
        SET @ResultCode = 'WAREHOUSE_SCOPE_REQUIRED';
        SET @ResultMsg = N'Tài khoản chưa được phân quyền kho';
        GOTO ReturnFailure;
    END;

    CREATE TABLE #RawItems (
        ItemID VARCHAR(50) NULL,
        Quantity DECIMAL(18,2) NULL,
        SoLuongTang DECIMAL(18,2) NOT NULL,
        UnitPrice DECIMAL(18,4) NULL,
        DiscountPercent DECIMAL(18,2) NOT NULL
    );

    INSERT #RawItems (ItemID, Quantity, SoLuongTang, UnitPrice, DiscountPercent)
    SELECT ItemID, Quantity, COALESCE(SoLuongTang, 0), UnitPrice, COALESCE(DiscountPercent, 0)
    FROM OPENJSON(@ItemList)
    WITH (
        ItemID VARCHAR(50) '$.ItemID',
        Quantity DECIMAL(18,2) '$.Quantity',
        SoLuongTang DECIMAL(18,2) '$.SoLuongTang',
        UnitPrice DECIMAL(18,4) '$.UnitPrice',
        DiscountPercent DECIMAL(18,2) '$.DiscountPercent'
    );

    IF NOT EXISTS (SELECT 1 FROM #RawItems)
       OR EXISTS (
            SELECT 1
            FROM #RawItems R
            LEFT JOIN dbo.CF_ItemTbl I ON I.ItemID = R.ItemID
            WHERE COALESCE(R.ItemID, '') = '' OR I.ItemID IS NULL
               OR NOT EXISTS
                  (
                      SELECT 1
                      FROM dbo.AI_BusinessRuleConfigTbl C
                      CROSS APPLY STRING_SPLIT(C.ConfigValue, ',') V
                      WHERE C.RuleCode = 'BR-STOCK-001'
                        AND C.RuleVersion = @StockRuleVersion
                        AND C.ConfigKey = 'SellableItemGroupIDs'
                        AND LTRIM(RTRIM(V.value)) = I.ItemGroupID
                  )
               OR CASE WHEN @BranchID = 'MB' THEN COALESCE(I.IsDisableMB, 0)
                       WHEN @BranchID = 'MN' THEN COALESCE(I.IsDisableMN, 0)
                       WHEN @BranchID = 'MT' THEN COALESCE(I.IsDisableMT, 0)
                       ELSE COALESCE(I.IsDisable, 0) END <> 0
               OR R.Quantity IS NULL OR R.Quantity <= 0 OR R.Quantity <> FLOOR(R.Quantity)
               OR R.SoLuongTang < 0 OR R.SoLuongTang <> FLOOR(R.SoLuongTang)
               OR R.UnitPrice IS NULL OR R.UnitPrice < 0
               OR R.DiscountPercent < 0 OR R.DiscountPercent > 100
       )
       OR EXISTS (
            SELECT 1 FROM #RawItems G
            WHERE G.UnitPrice = 0
              AND NOT EXISTS (SELECT 1 FROM #RawItems B WHERE B.ItemID = G.ItemID AND B.UnitPrice > 0)
       )
    BEGIN
        SET @ResultCode = 'INVALID_ITEM';
        SET @ResultMsg = N'Sản phẩm, số lượng, giá hoặc chiết khấu không hợp lệ';
        GOTO ReturnFailure;
    END;

    /* Fingerprint the caller intent before price/promotion/stock validation so a
       completed retry can return its cached result even when live data changed
       after the first commit. */
    SELECT @CanonicalItems = (
        SELECT ItemID AS itemId,
               Quantity AS quantity,
               SoLuongTang AS giftQuantity,
               UnitPrice AS unitPrice,
               DiscountPercent AS discountPercent
        FROM #RawItems
        ORDER BY ItemID, UnitPrice, Quantity, SoLuongTang, DiscountPercent
        FOR JSON PATH
    );

    SET @IdempotencyKeyHash = LOWER(CONVERT(CHAR(64), HASHBYTES('SHA2_256', CONVERT(VARBINARY(MAX), @IdempotencyKey)), 2));
    SET @VerifiedUserHash = LOWER(CONVERT(CHAR(64), HASHBYTES('SHA2_256', CONVERT(VARBINARY(MAX), LOWER(@Username))), 2));
    SET @RequestFingerprintHash = LOWER(CONVERT(CHAR(64), HASHBYTES('SHA2_256', CONVERT(VARBINARY(MAX),
        CONCAT(LOWER(@Username), '|', @ObjectID, '|', CONVERT(CHAR(10), CAST(@DocumentDate AS DATE), 23), '|',
               @BranchID, '|', CASE WHEN @DocumentID IN ('', 'AUTO_GEN') THEN 'AUTO_GEN' ELSE @DocumentID END, '|',
               COALESCE(@Memo, N''), '|', COALESCE(@Notes, N''), '|',
               COALESCE(@XaPhuong, N''), '|', COALESCE(@ThuDiTuyen, N''), '|', @CanonicalItems))), 2));

    SELECT @StoredStatus = Status,
           @StoredFingerprintHash = RequestFingerprintHash,
           @StoredDocumentID = ResultEntityID,
           @StoredMsg = ResultMsg,
           @StoredMsgType = ResultMsgType
    FROM dbo.AI_API_MutationIdempotency
    WHERE IdempotencyKeyHash = @IdempotencyKeyHash
      AND VerifiedUserHash = @VerifiedUserHash
      AND ApiCode = @ApiCode;

    IF @StoredStatus IS NOT NULL AND @StoredFingerprintHash <> @RequestFingerprintHash
    BEGIN
        SET @ResultCode = 'IDEMPOTENCY_CONFLICT';
        SET @ResultMsg = N'Khóa gửi lặp đã được dùng cho một nội dung đơn khác';
        GOTO ReturnFailure;
    END;

    IF @StoredStatus = 'COMPLETED' AND COALESCE(@StoredDocumentID, '') <> ''
    BEGIN
        BEGIN TRY
            BEGIN TRANSACTION;
            UPDATE dbo.AI_API_MutationIdempotency
            SET LastRequestID = @RequestID, UpdatedAt = SYSUTCDATETIME()
            WHERE IdempotencyKeyHash = @IdempotencyKeyHash
              AND VerifiedUserHash = @VerifiedUserHash
              AND ApiCode = @ApiCode;

            SET @AuditInfo = N'{"requestId":"' + STRING_ESCAPE(@RequestID, 'json')
                + N'","idempotencyKeyHash":"' + @IdempotencyKeyHash
                + N'","payloadFingerprint":"' + @RequestFingerprintHash
                + N'","capability":"' + @RequiredCapability
                + N'","branchId":"' + STRING_ESCAPE(@BranchID, 'json')
                + N'","outcome":"REPLAY"}';
            EXEC dbo.AI_WriteAuditLog @Username=@Username, @ActionType='REPLAY_DONHANG',
                 @TargetEntity=@ApiCode, @TargetID=@StoredDocumentID, @ExtraInfo=@AuditInfo;
            COMMIT TRANSACTION;
        END TRY
        BEGIN CATCH
            IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
            SET @ResultCode = 'AUDIT_WRITE_FAILED';
            SET @ResultMsg = N'Không thể ghi audit replay. Mã đối soát: ' + @RequestID;
            GOTO ReturnFailure;
        END CATCH;

        SELECT @StoredDocumentID AS DocumentID,
               COALESCE(NULLIF(@StoredMsg, N''), N'Đơn hàng đã được tạo trước đó') AS Msg,
               5 AS MsgType,
               @RequestID AS RequestID,
               CAST(1 AS BIT) AS IsReplay;
        RETURN;
    END;

    CREATE TABLE #Items (
        ItemID VARCHAR(50) NOT NULL PRIMARY KEY,
        Quantity DECIMAL(18,2) NOT NULL,
        SoLuongTang DECIMAL(18,2) NOT NULL,
        UnitPrice DECIMAL(18,4) NOT NULL,
        DiscountPercent DECIMAL(18,2) NOT NULL,
        ExpectedGiftQuantity DECIMAL(18,2) NOT NULL DEFAULT 0,
        ExpectedDiscountPercent DECIMAL(18,2) NOT NULL DEFAULT 0,
        ItemName NVARCHAR(500) NULL,
        PromotionNote NVARCHAR(MAX) NULL,
        DiemSanPham DECIMAL(18,2) NULL,
        StoreHouseID VARCHAR(50) NULL,
        AvailableQuantity DECIMAL(18,2) NULL
    );

    ;WITH Paid AS (
        SELECT ItemID,
               SUM(Quantity) AS Quantity,
               SUM(SoLuongTang) AS SoLuongTang,
               MAX(UnitPrice) AS UnitPrice,
               MAX(DiscountPercent) AS DiscountPercent,
               COUNT(DISTINCT UnitPrice) AS PriceCount,
               COUNT(DISTINCT DiscountPercent) AS DiscountCount
        FROM #RawItems
        WHERE UnitPrice > 0
        GROUP BY ItemID
    ), LegacyGift AS (
        SELECT ItemID, SUM(Quantity + SoLuongTang) AS GiftQuantity
        FROM #RawItems
        WHERE UnitPrice = 0
        GROUP BY ItemID
    )
    INSERT #Items (
        ItemID, Quantity, SoLuongTang, UnitPrice, DiscountPercent,
        ItemName, PromotionNote, DiemSanPham
    )
    SELECT B.ItemID,
           B.Quantity,
           B.SoLuongTang + COALESCE(G.GiftQuantity, 0),
           B.UnitPrice,
           B.DiscountPercent,
           I.ItemName,
           P.GhiChu,
           P.DiemSanPham
    FROM Paid B
    JOIN dbo.CF_ItemTbl I ON I.ItemID = B.ItemID
    OUTER APPLY (
        SELECT TOP (1) UnitPrice, DiemSanPham, GhiChu
        FROM dbo.AR_LayGiaSanPhamFnc(CAST(@DocumentDate AS DATE), @ObjectID, B.ItemID)
    ) P
    LEFT JOIN LegacyGift G ON G.ItemID = B.ItemID
    WHERE B.PriceCount = 1 AND B.DiscountCount = 1
      AND P.UnitPrice IS NOT NULL
      AND ABS(B.UnitPrice - P.UnitPrice) <= 0.01;

    IF (SELECT COUNT(*) FROM #Items) <> (SELECT COUNT(DISTINCT ItemID) FROM #RawItems WHERE UnitPrice > 0)
       OR EXISTS (SELECT 1 FROM #RawItems WHERE UnitPrice > 0 AND ItemID NOT IN (SELECT ItemID FROM #Items))
    BEGIN
        SET @ResultCode = 'PRICE_CHANGED';
        SET @ResultMsg = N'Giá sản phẩm đã thay đổi hoặc không còn hợp lệ. Vui lòng tải lại danh sách hàng';
        GOTO ReturnFailure;
    END;

    /* Recalculate the current general-customer promotion from the SQL price note.
       The client values are accepted only when they match this server result. */
    DECLARE @PromoItemID VARCHAR(50), @PromoQuantity INT, @PromoNote NVARCHAR(MAX);
    DECLARE @PromoText NVARCHAR(MAX), @PromoUpper NVARCHAR(MAX), @Scan INT, @PlusPos INT;
    DECLARE @LeftPos INT, @LeftEnd INT, @RightPos INT, @RightEnd INT;
    DECLARE @BuyQty INT, @GiftQty INT, @BestBuyQty INT, @BestGiftQty INT;
    DECLARE @KhhdPos1 INT, @KhhdPos2 INT, @KhhdPos INT;
    DECLARE @LtPos INT, @ThresholdStart INT, @ThresholdEnd INT, @ThresholdQty INT;
    DECLARE @CkPos INT, @CkLength INT, @PercentPos INT, @DiscountText NVARCHAR(100), @ExpectedDiscount DECIMAL(18,2);

    DECLARE PromotionCursor CURSOR LOCAL FAST_FORWARD FOR
        SELECT ItemID, CONVERT(INT, Quantity), COALESCE(PromotionNote, N'') FROM #Items;
    OPEN PromotionCursor;
    FETCH NEXT FROM PromotionCursor INTO @PromoItemID, @PromoQuantity, @PromoNote;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @PromoText = LTRIM(RTRIM(COALESCE(@PromoNote, N'')));
        SET @PromoUpper = UPPER(@PromoText);
        SET @KhhdPos1 = CHARINDEX(N'KHHĐ', @PromoUpper);
        SET @KhhdPos2 = CHARINDEX(N'KHHD', @PromoUpper);
        SET @KhhdPos = CASE WHEN @KhhdPos1 > 0 AND @KhhdPos2 > 0 THEN IIF(@KhhdPos1 < @KhhdPos2, @KhhdPos1, @KhhdPos2)
                            WHEN @KhhdPos1 > 0 THEN @KhhdPos1 ELSE @KhhdPos2 END;
        IF @KhhdPos > 0 SET @PromoText = LEFT(@PromoText, @KhhdPos - 1);
        SET @PromoUpper = UPPER(@PromoText);
        SET @BestBuyQty = 0;
        SET @BestGiftQty = 0;

        IF @PromoUpper NOT LIKE N'%NGUYÊN GIÁ%'
        BEGIN
            SET @Scan = 1;
            SET @PlusPos = CHARINDEX('+', @PromoText, @Scan);
            WHILE @PlusPos > 0
            BEGIN
                SET @LeftPos = @PlusPos - 1;
                WHILE @LeftPos > 0 AND SUBSTRING(@PromoText, @LeftPos, 1) = ' ' SET @LeftPos -= 1;
                SET @LeftEnd = @LeftPos;
                WHILE @LeftPos > 0 AND SUBSTRING(@PromoText, @LeftPos, 1) LIKE '[0-9]' SET @LeftPos -= 1;
                SET @LeftPos += 1;

                SET @RightPos = @PlusPos + 1;
                WHILE @RightPos <= LEN(@PromoText) AND SUBSTRING(@PromoText, @RightPos, 1) = ' ' SET @RightPos += 1;
                SET @RightEnd = @RightPos;
                WHILE @RightEnd <= LEN(@PromoText) AND SUBSTRING(@PromoText, @RightEnd, 1) LIKE '[0-9]' SET @RightEnd += 1;

                SET @BuyQty = TRY_CONVERT(INT, SUBSTRING(@PromoText, @LeftPos, @LeftEnd - @LeftPos + 1));
                SET @GiftQty = TRY_CONVERT(INT, SUBSTRING(@PromoText, @RightPos, @RightEnd - @RightPos));
                IF COALESCE(@BuyQty, 0) > 0 AND COALESCE(@GiftQty, 0) > 0
                   AND @PromoQuantity >= @BuyQty AND @BuyQty > @BestBuyQty
                BEGIN
                    SET @BestBuyQty = @BuyQty;
                    SET @BestGiftQty = @GiftQty;
                END;
                SET @Scan = @PlusPos + 1;
                SET @PlusPos = CHARINDEX('+', @PromoText, @Scan);
            END;
        END;

        IF @BestBuyQty > 0
        BEGIN
            UPDATE #Items
            SET ExpectedGiftQuantity = FLOOR(@PromoQuantity * 1.0 / @BestBuyQty) * @BestGiftQty,
                ExpectedDiscountPercent = 0
            WHERE ItemID = @PromoItemID;
        END
        ELSE IF @PromoUpper NOT LIKE N'%NGUYÊN GIÁ%'
        BEGIN
            SET @LtPos = CHARINDEX('<', @PromoText);
            SET @ThresholdQty = NULL;
            SET @ExpectedDiscount = NULL;
            IF @LtPos > 0
            BEGIN
                SET @ThresholdStart = @LtPos + 1;
                WHILE @ThresholdStart <= LEN(@PromoText) AND SUBSTRING(@PromoText, @ThresholdStart, 1) = ' ' SET @ThresholdStart += 1;
                SET @ThresholdEnd = @ThresholdStart;
                WHILE @ThresholdEnd <= LEN(@PromoText) AND SUBSTRING(@PromoText, @ThresholdEnd, 1) LIKE '[0-9]' SET @ThresholdEnd += 1;
                SET @ThresholdQty = TRY_CONVERT(INT, SUBSTRING(@PromoText, @ThresholdStart, @ThresholdEnd - @ThresholdStart));

                SET @CkPos = CHARINDEX('CK', @PromoUpper, @ThresholdEnd);
                SET @CkLength = 2;
                IF @CkPos = 0
                BEGIN
                    SET @CkPos = CHARINDEX(N'CHIẾT KHẤU', @PromoUpper, @ThresholdEnd);
                    SET @CkLength = LEN(N'CHIẾT KHẤU');
                END;
                SET @PercentPos = CASE WHEN @CkPos > 0 THEN CHARINDEX('%', @PromoText, @CkPos + @CkLength) ELSE 0 END;
                IF @CkPos > 0 AND @PercentPos > @CkPos
                BEGIN
                    SET @DiscountText = SUBSTRING(@PromoText, @CkPos + @CkLength, @PercentPos - @CkPos - @CkLength);
                    SET @DiscountText = REPLACE(REPLACE(REPLACE(REPLACE(UPPER(@DiscountText), N'BẰNG', ''), '=', ''), ' ', ''), ',', '.');
                    SET @ExpectedDiscount = TRY_CONVERT(DECIMAL(18,2), @DiscountText);
                END;
            END;
            IF COALESCE(@ThresholdQty, 0) > 0 AND @PromoQuantity < @ThresholdQty AND @ExpectedDiscount IS NOT NULL
                UPDATE #Items SET ExpectedDiscountPercent = @ExpectedDiscount WHERE ItemID = @PromoItemID;
        END;

        FETCH NEXT FROM PromotionCursor INTO @PromoItemID, @PromoQuantity, @PromoNote;
    END;
    CLOSE PromotionCursor;
    DEALLOCATE PromotionCursor;

    IF EXISTS (
        SELECT 1 FROM #Items
        WHERE ABS(SoLuongTang - ExpectedGiftQuantity) > 0.01
           OR ABS(DiscountPercent - ExpectedDiscountPercent) > 0.01
    )
    BEGIN
        SET @ResultCode = 'PROMOTION_CHANGED';
        SET @ResultMsg = N'Chương trình bán hàng đã thay đổi. Vui lòng tải lại sản phẩm trước khi tạo đơn';
        GOTO ReturnFailure;
    END;

    BEGIN TRY
        BEGIN TRANSACTION;

        SELECT @StoredStatus = Status,
               @StoredFingerprintHash = RequestFingerprintHash,
               @StoredDocumentID = ResultEntityID,
               @StoredMsg = ResultMsg,
               @StoredMsgType = ResultMsgType
        FROM dbo.AI_API_MutationIdempotency WITH (UPDLOCK, HOLDLOCK)
        WHERE IdempotencyKeyHash = @IdempotencyKeyHash
          AND VerifiedUserHash = @VerifiedUserHash
          AND ApiCode = @ApiCode;

        IF @StoredStatus IS NOT NULL
        BEGIN
            IF @StoredFingerprintHash IS NULL OR @StoredFingerprintHash <> @RequestFingerprintHash
            BEGIN
                SET @ResultCode = 'IDEMPOTENCY_CONFLICT';
                SET @ResultMsg = N'Khóa gửi lặp đã được dùng cho một nội dung đơn khác';
                THROW 51001, @ResultMsg, 1;
            END;
            IF @StoredStatus = 'COMPLETED' AND COALESCE(@StoredDocumentID, '') <> ''
            BEGIN
                UPDATE dbo.AI_API_MutationIdempotency
                SET LastRequestID = @RequestID, UpdatedAt = SYSUTCDATETIME()
                WHERE IdempotencyKeyHash = @IdempotencyKeyHash
                  AND VerifiedUserHash = @VerifiedUserHash
                  AND ApiCode = @ApiCode;

                SET @AuditInfo = N'{"requestId":"' + STRING_ESCAPE(@RequestID, 'json')
                    + N'","idempotencyKeyHash":"' + @IdempotencyKeyHash
                    + N'","payloadFingerprint":"' + @RequestFingerprintHash
                    + N'","capability":"' + @RequiredCapability
                    + N'","branchId":"' + STRING_ESCAPE(@BranchID, 'json')
                    + N'","outcome":"REPLAY"}';
                EXEC dbo.AI_WriteAuditLog @Username=@Username, @ActionType='REPLAY_DONHANG',
                     @TargetEntity=@ApiCode, @TargetID=@StoredDocumentID, @ExtraInfo=@AuditInfo;

                COMMIT TRANSACTION;
                SELECT @StoredDocumentID AS DocumentID,
                       COALESCE(NULLIF(@StoredMsg, N''), N'Đơn hàng đã được tạo trước đó') AS Msg,
                       5 AS MsgType,
                       @RequestID AS RequestID,
                       CAST(1 AS BIT) AS IsReplay;
                RETURN;
            END;

            SET @ResultCode = 'IDEMPOTENCY_IN_PROGRESS';
            SET @ResultMsg = N'Yêu cầu trùng đang được xử lý';
            THROW 51002, @ResultMsg, 1;
        END;

        INSERT dbo.AI_API_MutationIdempotency (
            IdempotencyKeyHash, VerifiedUserHash, ApiCode, RequestFingerprintHash,
            Status, FirstRequestID, LastRequestID
        ) VALUES (
            @IdempotencyKeyHash, @VerifiedUserHash, @ApiCode, @RequestFingerprintHash,
            'PENDING', @RequestID, @RequestID
        );

        IF @DocumentID <> '' AND @DocumentID <> 'AUTO_GEN'
        BEGIN
            IF EXISTS (SELECT 1 FROM dbo.AR_OrderTbl WITH (UPDLOCK, HOLDLOCK) WHERE DocumentID = @DocumentID)
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM dbo.AR_OrderTbl
                    WHERE DocumentID = @DocumentID
                      AND (UserCreate <> LEFT(@Username, 30) OR ObjectID <> @ObjectID OR BranchID <> @BranchID OR EmployeeID <> @EmployeeID
                           OR CAST(DocumentDate AS DATE) <> CAST(@DocumentDate AS DATE)
                           OR COALESCE(Memo, N'') <> COALESCE(@Memo, N'')
                           OR COALESCE(Notes, N'') <> COALESCE(@Notes, N'')
                           OR COALESCE(XaPhuong, N'') <> COALESCE(@XaPhuong, N'')
                           OR COALESCE(ThuTrongTuan, N'') <> COALESCE(@ThuDiTuyen, N''))
                )
                OR EXISTS (
                    SELECT ItemID, UnitPrice, SUM(Quantity), SUM(COALESCE(SoLuongTang, 0)), MAX(DiscountPercent)
                    FROM dbo.AR_OrderDetailTbl WHERE DocumentID = @DocumentID GROUP BY ItemID, UnitPrice
                    EXCEPT
                    SELECT ItemID, UnitPrice, Quantity, SoLuongTang, DiscountPercent FROM #Items
                )
                OR EXISTS (
                    SELECT ItemID, UnitPrice, Quantity, SoLuongTang, DiscountPercent FROM #Items
                    EXCEPT
                    SELECT ItemID, UnitPrice, SUM(Quantity), SUM(COALESCE(SoLuongTang, 0)), MAX(DiscountPercent)
                    FROM dbo.AR_OrderDetailTbl WHERE DocumentID = @DocumentID GROUP BY ItemID, UnitPrice
                )
                BEGIN
                    SET @ResultCode = 'DOCUMENT_ID_CONFLICT';
                    SET @ResultMsg = N'Mã đơn hàng đã được dùng cho một nội dung khác';
                    THROW 51003, @ResultMsg, 1;
                END;

                UPDATE dbo.AI_API_MutationIdempotency
                SET Status='COMPLETED', ResultEntityID=@DocumentID,
                    ResultMsg=N'Đơn hàng đã được tạo trước đó', ResultMsgType=5,
                    LastRequestID=@RequestID, UpdatedAt=SYSUTCDATETIME(), CompletedAt=SYSUTCDATETIME()
                WHERE IdempotencyKeyHash=@IdempotencyKeyHash AND VerifiedUserHash=@VerifiedUserHash AND ApiCode=@ApiCode;

                SET @AuditInfo = N'{"requestId":"' + STRING_ESCAPE(@RequestID, 'json')
                    + N'","idempotencyKeyHash":"' + @IdempotencyKeyHash
                    + N'","payloadFingerprint":"' + @RequestFingerprintHash
                    + N'","capability":"' + @RequiredCapability
                    + N'","branchId":"' + STRING_ESCAPE(@BranchID, 'json')
                    + N'","outcome":"REPLAY_BY_DOCUMENT_ID"}';
                EXEC dbo.AI_WriteAuditLog @Username=@Username, @ActionType='REPLAY_DONHANG',
                     @TargetEntity=@ApiCode, @TargetID=@DocumentID, @ExtraInfo=@AuditInfo;

                COMMIT TRANSACTION;
                SELECT @DocumentID AS DocumentID, N'Đơn hàng đã được tạo trước đó' AS Msg, 5 AS MsgType,
                       @RequestID AS RequestID, CAST(1 AS BIT) AS IsReplay;
                RETURN;
            END;
        END
        ELSE
        BEGIN
            DECLARE @Prefix VARCHAR(20) = 'D' + @BranchID
                + RIGHT('0' + CAST(MONTH(@DocumentDate) AS VARCHAR), 2)
                + RIGHT(CAST(YEAR(@DocumentDate) AS VARCHAR), 2) + '/';
            DECLARE @MaxNum INT;
            SELECT @MaxNum = COALESCE(MAX(TRY_CAST(SUBSTRING(DocumentID, LEN(@Prefix) + 1, 99) AS INT)), 0)
            FROM dbo.AR_OrderTbl WITH (UPDLOCK, HOLDLOCK)
            WHERE DocumentID LIKE @Prefix + '%';
            SET @DocumentID = @Prefix + CAST(@MaxNum + 1 AS VARCHAR);
        END;

        CREATE TABLE #StoreStock (
            ItemID VARCHAR(50) NOT NULL,
            StoreHouseID VARCHAR(50) NOT NULL,
            AvailableQuantity DECIMAL(18,2) NOT NULL,
            RankNo INT NOT NULL,
            PRIMARY KEY (ItemID, StoreHouseID)
        );

        ;WITH Physical AS (
            SELECT T.ItemID, T.StoreHouseID,
                   SUM(CASE WHEN T.ExpireDate IS NULL OR CAST(T.ExpireDate AS DATE) >= CAST(@DocumentDate AS DATE)
                            THEN T.Quantity ELSE 0 END) AS PhysicalQuantity
            FROM dbo.IV_StockTransactionTbl T WITH (UPDLOCK, HOLDLOCK)
            JOIN #Items I ON I.ItemID = T.ItemID
            WHERE T.StoreHouseID IN (SELECT StoreHouseID FROM @AllowedStores)
            GROUP BY T.ItemID, T.StoreHouseID
        ), Reserved AS (
            SELECT D.ItemID, D.StoreHouseID,
                   SUM(COALESCE(D.Quantity, 0) + COALESCE(D.SoLuongTang, 0)) AS ReservedQuantity
            FROM dbo.AR_OrderDetailTbl D WITH (UPDLOCK, HOLDLOCK)
            JOIN dbo.AR_OrderTbl O WITH (HOLDLOCK) ON O.DocumentID = D.DocumentID
            JOIN #Items I ON I.ItemID = D.ItemID
            WHERE COALESCE(D.StoreHouseID, '') <> ''
              AND EXISTS
                  (
                      SELECT 1
                      FROM dbo.AI_BusinessRuleConfigTbl C
                      CROSS APPLY STRING_SPLIT(C.ConfigValue, ',') V
                      WHERE C.RuleCode = 'BR-STOCK-001'
                        AND C.RuleVersion = @StockRuleVersion
                        AND C.ConfigKey = 'ReservedOrderStatusIDs'
                        AND TRY_CONVERT(INT, LTRIM(RTRIM(V.value))) = O.StatusID
                  )
              AND O.DocumentID <> @DocumentID
            GROUP BY D.ItemID, D.StoreHouseID
        ), Ranked AS (
            SELECT P.ItemID, P.StoreHouseID,
                   P.PhysicalQuantity - COALESCE(R.ReservedQuantity, 0) AS AvailableQuantity,
                   ROW_NUMBER() OVER (
                       PARTITION BY P.ItemID
                       ORDER BY P.PhysicalQuantity - COALESCE(R.ReservedQuantity, 0) DESC, P.StoreHouseID
                   ) AS RankNo
            FROM Physical P
            LEFT JOIN Reserved R ON R.ItemID = P.ItemID AND R.StoreHouseID = P.StoreHouseID
        )
        INSERT #StoreStock (ItemID, StoreHouseID, AvailableQuantity, RankNo)
        SELECT ItemID, StoreHouseID, AvailableQuantity, RankNo FROM Ranked;

        UPDATE I
        SET StoreHouseID = S.StoreHouseID,
            AvailableQuantity = S.AvailableQuantity
        FROM #Items I
        JOIN #StoreStock S ON S.ItemID = I.ItemID AND S.RankNo = 1;

        IF EXISTS (
            SELECT 1 FROM #Items
            WHERE StoreHouseID IS NULL OR Quantity + SoLuongTang > COALESCE(AvailableQuantity, 0)
        )
        BEGIN
            SET @ResultCode = 'INSUFFICIENT_STOCK';
            SET @ResultMsg = N'Số lượng mua và tặng vượt tồn khả dụng tại một kho được cấp';
            THROW 51004, @ResultMsg, 1;
        END;

        INSERT dbo.AR_OrderTbl (
            DocumentID, DocumentDate, EmployeeID, ManagerID, CeoID,
            ObjectID, BranchID, Memo, Notes, UserCreate, DateCreate,
            XaPhuong, ThuTrongTuan, StatusID, Phone
        ) VALUES (
            @DocumentID, @DocumentDate, @EmployeeID, @ManagerID, @CeoID,
            @ObjectID, @BranchID, @Memo, @Notes, LEFT(@Username, 30), GETDATE(),
            @XaPhuong, @ThuDiTuyen, 0, @Phone
        );

        INSERT dbo.AR_OrderDetailTbl (
            UserAutoID, DocumentID, ItemID, UnitPrice, Quantity, SoLuongTang,
            Amount, DiscountPercent, DiscountAmount, TotalAmount,
            DiemSanPham, DiemTichLuy, Notes, StoreHouseID, UserCreate, DateCreate
        )
        SELECT CONVERT(VARCHAR(40), NEWID()), @DocumentID, ItemID, UnitPrice, Quantity, SoLuongTang,
               Quantity * UnitPrice,
               DiscountPercent,
               Quantity * UnitPrice * DiscountPercent / 100.0,
               Quantity * UnitPrice * (1.0 - DiscountPercent / 100.0),
               COALESCE(DiemSanPham, 0),
               Quantity * COALESCE(DiemSanPham, 0),
               N'', StoreHouseID, LEFT(@Username, 30), GETDATE()
        FROM #Items;

        EXEC dbo.AR_Order_AfterSaveStp @DocumentID;

        UPDATE dbo.AR_OrderTbl
        SET BaseTotal = COALESCE((SELECT SUM(TotalAmount) FROM dbo.AR_OrderDetailTbl WHERE DocumentID = @DocumentID), 0)
        WHERE DocumentID = @DocumentID;

        UPDATE dbo.AI_API_MutationIdempotency
        SET Status='COMPLETED', ResultEntityID=@DocumentID,
            ResultMsg=N'Tạo đơn hàng thành công', ResultMsgType=5,
            LastRequestID=@RequestID, UpdatedAt=SYSUTCDATETIME(), CompletedAt=SYSUTCDATETIME()
        WHERE IdempotencyKeyHash=@IdempotencyKeyHash AND VerifiedUserHash=@VerifiedUserHash AND ApiCode=@ApiCode;

        SET @AuditInfo = N'{"requestId":"' + STRING_ESCAPE(@RequestID, 'json')
            + N'","idempotencyKeyHash":"' + @IdempotencyKeyHash
            + N'","payloadFingerprint":"' + @RequestFingerprintHash
            + N'","capability":"' + @RequiredCapability
            + N'","outcome":"CREATED","branchId":"' + STRING_ESCAPE(@BranchID, 'json') + N'"}';
        EXEC dbo.AI_WriteAuditLog @Username=@Username, @ActionType='CREATE_DONHANG',
             @TargetEntity=@ApiCode, @TargetID=@DocumentID, @ExtraInfo=@AuditInfo;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        SET @InternalError = ERROR_MESSAGE();
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        IF ERROR_NUMBER() BETWEEN 51001 AND 51004
        BEGIN
            IF @ResultCode = '' SET @ResultCode = 'ORDER_VALIDATION_FAILED';
            IF @ResultMsg = '' SET @ResultMsg = @InternalError;
        END
        ELSE
        BEGIN
            SET @ResultCode = 'SYSTEM_ERROR';
            SET @ResultMsg = N'Hệ thống chưa thể tạo đơn hàng. Mã đối soát: ' + @RequestID;
        END;
        GOTO ReturnFailure;
    END CATCH;

    SELECT @DocumentID AS DocumentID, N'Tạo đơn hàng thành công' AS Msg, 5 AS MsgType,
           @RequestID AS RequestID, CAST(0 AS BIT) AS IsReplay;
    RETURN;

ReturnFailure:
    SET @AuditInfo = N'{"requestId":"' + STRING_ESCAPE(COALESCE(@RequestID, ''), 'json')
        + N'","idempotencyKeyHash":' + CASE WHEN @IdempotencyKeyHash IS NULL THEN N'null' ELSE N'"' + @IdempotencyKeyHash + N'"' END
        + N',"payloadFingerprint":' + CASE WHEN @RequestFingerprintHash IS NULL THEN N'null' ELSE N'"' + @RequestFingerprintHash + N'"' END
        + N',"capability":"' + @RequiredCapability
        + N'","branchId":"' + STRING_ESCAPE(COALESCE(@BranchID, ''), 'json')
        + N'","resultCode":"' + STRING_ESCAPE(COALESCE(@ResultCode, 'UNKNOWN'), 'json')
        + N'","outcome":"FAILED"'
        + CASE WHEN @InternalError <> N'' THEN N',"internalError":"' + STRING_ESCAPE(LEFT(@InternalError, 1000), 'json') + N'"' ELSE N'' END
        + N'}';
    BEGIN TRY
        IF @ResultCode <> 'AUDIT_UNAVAILABLE' AND @Username <> '' AND @RequestID LIKE 'req-%'
            EXEC dbo.AI_WriteAuditLog @Username=@Username, @ActionType='CREATE_DONHANG_FAILED',
                 @TargetEntity=@ApiCode, @TargetID=NULL, @ExtraInfo=@AuditInfo;
    END TRY
    BEGIN CATCH
        SET @ResultCode = 'AUDIT_WRITE_FAILED';
        SET @ResultMsg = N'Không thể ghi audit mutation. Không có dữ liệu đơn hàng nào được commit. Mã đối soát: ' + COALESCE(@RequestID, '');
    END CATCH;
    SELECT NULL AS DocumentID, @ResultMsg AS Msg, 1 AS MsgType,
           NULLIF(@RequestID, '') AS RequestID, @ResultCode AS Code;
END;
GO
